# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'geradorMegaSena.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GeradorMegaSena(object):
    def setupUi(self, GeradorMegaSena):
        GeradorMegaSena.setObjectName("GeradorMegaSena")
        GeradorMegaSena.resize(620, 400)
        GeradorMegaSena.setStyleSheet("background-color:rgb(36, 31, 49)qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255))")
        self.centralwidget = QtWidgets.QWidget(GeradorMegaSena)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.NomeDoPrograma = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.NomeDoPrograma.setFont(font)
        self.NomeDoPrograma.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.NomeDoPrograma.setAutoFillBackground(False)
        self.NomeDoPrograma.setStyleSheet("background-color:rgb(36, 31, 49)qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255))")
        self.NomeDoPrograma.setTextFormat(QtCore.Qt.RichText)
        self.NomeDoPrograma.setAlignment(QtCore.Qt.AlignCenter)
        self.NomeDoPrograma.setObjectName("NomeDoPrograma")
        self.verticalLayout_2.addWidget(self.NomeDoPrograma)
        self.resultado = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.resultado.setFont(font)
        self.resultado.setStyleSheet("background-color:rgb(36, 31, 49)qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255))")
        self.resultado.setText("")
        self.resultado.setAlignment(QtCore.Qt.AlignCenter)
        self.resultado.setObjectName("resultado")
        self.verticalLayout_2.addWidget(self.resultado)
        self.btnGerador = QtWidgets.QPushButton(self.frame)
        self.btnGerador.setObjectName("btnGerador")
        self.verticalLayout_2.addWidget(self.btnGerador)
        self.verticalLayout.addWidget(self.frame)
        GeradorMegaSena.setCentralWidget(self.centralwidget)

        self.retranslateUi(GeradorMegaSena)
        QtCore.QMetaObject.connectSlotsByName(GeradorMegaSena)

    def retranslateUi(self, GeradorMegaSena):
        _translate = QtCore.QCoreApplication.translate
        GeradorMegaSena.setWindowTitle(_translate("GeradorMegaSena", "Gerador MegaSena"))
        self.NomeDoPrograma.setText(_translate("GeradorMegaSena", "Gerador de números da Mega Sena"))
        self.btnGerador.setText(_translate("GeradorMegaSena", "Gerar Números"))
